name: Build data.json

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Validate images and captions
        run: python scripts/build_data.py --check

  generate:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build data.json
        run: python scripts/build_data.py
      - name: Commit data.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update data.json'
          file_pattern: data.json
